/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

'use strict';

// Inspired by https://github.com/airbnb/javascript but less opinionated.

// We use eslint-loader so even warnings are very visible.
// This is why we only use "WARNING" level for potential errors,
// and we don't use "ERROR" level at all.

// In the future, we might create a separate list of rules for production.
// It would probably be more strict.

module.exports = {
  root: true,

  parser: 'babel-eslint',

  plugins: ['import', 'flowtype', 'jsx-a11y', 'react'],

  env: {
    commonjs: true,
    es6: true,
    jest: true,
    node: true,
  },

  globals: {
    addEventListener: false,
    alert: false,
    AnalyserNode: false,
    Animation: false,
    AnimationEffectReadOnly: false,
    AnimationEffectTiming: false,
    AnimationEffectTimingReadOnly: false,
    AnimationEvent: false,
    AnimationPlaybackEvent: false,
    AnimationTimeline: false,
    applicationCache: false,
    ApplicationCache: false,
    ApplicationCacheErrorEvent: false,
    atob: false,
    Attr: false,
    Audio: false,
    AudioBuffer: false,
    AudioBufferSourceNode: false,
    AudioContext: false,
    AudioDestinationNode: false,
    AudioListener: false,
    AudioNode: false,
    AudioParam: false,
    AudioProcessingEvent: false,
    AutocompleteErrorEvent: false,
    BarProp: false,
    BatteryManager: false,
    BeforeUnloadEvent: false,
    BiquadFilterNode: false,
    Blob: false,
    blur: false,
    btoa: false,
    Cache: false,
    caches: false,
    CacheStorage: false,
    cancelAnimationFrame: false,
    CanvasGradient: false,
    CanvasPattern: false,
    CanvasRenderingContext2D: false,
    CDATASection: false,
    ChannelMergerNode: false,
    ChannelSplitterNode: false,
    CharacterData: false,
    clearInterval: false,
    clearTimeout: false,
    clientInformation: false,
    ClientRect: false,
    ClientRectList: false,
    ClipboardEvent: false,
    CloseEvent: false,
    Comment: false,
    CompositionEvent: false,
    confirm: false,
    console: false,
    ConvolverNode: false,
    Credential: false,
    CredentialsContainer: false,
    crypto: false,
    Crypto: false,
    CryptoKey: false,
    CSS: false,
    CSSAnimation: false,
    CSSFontFaceRule: false,
    CSSImportRule: false,
    CSSKeyframeRule: false,
    CSSKeyframesRule: false,
    CSSMediaRule: false,
    CSSPageRule: false,
    CSSRule: false,
    CSSRuleList: false,
    CSSStyleDeclaration: false,
    CSSStyleRule: false,
    CSSStyleSheet: false,
    CSSSupportsRule: false,
    CSSTransition: false,
    CSSUnknownRule: false,
    CSSViewportRule: false,
    customElements: false,
    CustomEvent: false,
    DataTransfer: false,
    DataTransferItem: false,
    DataTransferItemList: false,
    Debug: false,
    defaultStatus: false,
    defaultstatus: false,
    DelayNode: false,
    DeviceMotionEvent: false,
    DeviceOrientationEvent: false,
    devicePixelRatio: false,
    dispatchEvent: false,
    document: false,
    Document: false,
    DocumentFragment: false,
    DocumentTimeline: false,
    DocumentType: false,
    DOMError: false,
    DOMException: false,
    DOMImplementation: false,
    DOMParser: false,
    DOMSettableTokenList: false,
    DOMStringList: false,
    DOMStringMap: false,
    DOMTokenList: false,
    DragEvent: false,
    DynamicsCompressorNode: false,
    Element: false,
    ElementTimeControl: false,
    ErrorEvent: false,
    event: false,
    Event: false,
    EventSource: false,
    EventTarget: false,
    external: false,
    FederatedCredential: false,
    fetch: false,
    File: false,
    FileError: false,
    FileList: false,
    FileReader: false,
    find: false,
    FocusEvent: false,
    FontFace: false,
    FormData: false,
    frameElement: false,
    frames: false,
    GainNode: false,
    Gamepad: false,
    GamepadButton: false,
    GamepadEvent: false,
    getComputedStyle: false,
    getSelection: false,
    HashChangeEvent: false,
    Headers: false,
    History: false,
    HTMLAllCollection: false,
    HTMLAnchorElement: false,
    HTMLAppletElement: false,
    HTMLAreaElement: false,
    HTMLAudioElement: false,
    HTMLBaseElement: false,
    HTMLBlockquoteElement: false,
    HTMLBodyElement: false,
    HTMLBRElement: false,
    HTMLButtonElement: false,
    HTMLCanvasElement: false,
    HTMLCollection: false,
    HTMLContentElement: false,
    HTMLDataListElement: false,
    HTMLDetailsElement: false,
    HTMLDialogElement: false,
    HTMLDirectoryElement: false,
    HTMLDivElement: false,
    HTMLDListElement: false,
    HTMLDocument: false,
    HTMLElement: false,
    HTMLEmbedElement: false,
    HTMLFieldSetElement: false,
    HTMLFontElement: false,
    HTMLFormControlsCollection: false,
    HTMLFormElement: false,
    HTMLFrameElement: false,
    HTMLFrameSetElement: false,
    HTMLHeadElement: false,
    HTMLHeadingElement: false,
    HTMLHRElement: false,
    HTMLHtmlElement: false,
    HTMLIFrameElement: false,
    HTMLImageElement: false,
    HTMLInputElement: false,
    HTMLIsIndexElement: false,
    HTMLKeygenElement: false,
    HTMLLabelElement: false,
    HTMLLayerElement: false,
    HTMLLegendElement: false,
    HTMLLIElement: false,
    HTMLLinkElement: false,
    HTMLMapElement: false,
    HTMLMarqueeElement: false,
    HTMLMediaElement: false,
    HTMLMenuElement: false,
    HTMLMetaElement: false,
    HTMLMeterElement: false,
    HTMLModElement: false,
    HTMLObjectElement: false,
    HTMLOListElement: false,
    HTMLOptGroupElement: false,
    HTMLOptionElement: false,
    HTMLOptionsCollection: false,
    HTMLOutputElement: false,
    HTMLParagraphElement: false,
    HTMLParamElement: false,
    HTMLPictureElement: false,
    HTMLPreElement: false,
    HTMLProgressElement: false,
    HTMLQuoteElement: false,
    HTMLScriptElement: false,
    HTMLSelectElement: false,
    HTMLShadowElement: false,
    HTMLSourceElement: false,
    HTMLSpanElement: false,
    HTMLStyleElement: false,
    HTMLTableCaptionElement: false,
    HTMLTableCellElement: false,
    HTMLTableColElement: false,
    HTMLTableElement: false,
    HTMLTableRowElement: false,
    HTMLTableSectionElement: false,
    HTMLTemplateElement: false,
    HTMLTextAreaElement: false,
    HTMLTitleElement: false,
    HTMLTrackElement: false,
    HTMLUListElement: false,
    HTMLUnknownElement: false,
    HTMLVideoElement: false,
    IDBCursor: false,
    IDBCursorWithValue: false,
    IDBDatabase: false,
    IDBEnvironment: false,
    IDBFactory: false,
    IDBIndex: false,
    IDBKeyRange: false,
    IDBObjectStore: false,
    IDBOpenDBRequest: false,
    IDBRequest: false,
    IDBTransaction: false,
    IDBVersionChangeEvent: false,
    Image: false,
    ImageBitmap: false,
    ImageData: false,
    indexedDB: false,
    innerHeight: false,
    innerWidth: false,
    InputEvent: false,
    InputMethodContext: false,
    IntersectionObserver: false,
    IntersectionObserverEntry: false,
    Intl: false,
    KeyboardEvent: false,
    KeyframeEffect: false,
    KeyframeEffectReadOnly: false,
    localStorage: false,
    Location: false,
    locationbar: false,
    matchMedia: false,
    MediaElementAudioSourceNode: false,
    MediaEncryptedEvent: false,
    MediaError: false,
    MediaKeyError: false,
    MediaKeyEvent: false,
    MediaKeyMessageEvent: false,
    MediaKeys: false,
    MediaKeySession: false,
    MediaKeyStatusMap: false,
    MediaKeySystemAccess: false,
    MediaList: false,
    MediaQueryList: false,
    MediaQueryListEvent: false,
    MediaSource: false,
    MediaRecorder: false,
    MediaStream: false,
    MediaStreamAudioDestinationNode: false,
    MediaStreamAudioSourceNode: false,
    MediaStreamEvent: false,
    MediaStreamTrack: false,
    MessageChannel: false,
    MessageEvent: false,
    MessagePort: false,
    MIDIAccess: false,
    MIDIConnectionEvent: false,
    MIDIInput: false,
    MIDIInputMap: false,
    MIDIMessageEvent: false,
    MIDIOutput: false,
    MIDIOutputMap: false,
    MIDIPort: false,
    MimeType: false,
    MimeTypeArray: false,
    MouseEvent: false,
    moveBy: false,
    moveTo: false,
    MutationEvent: false,
    MutationObserver: false,
    MutationRecord: false,
    NamedNodeMap: false,
    navigator: false,
    Navigator: false,
    Node: false,
    NodeFilter: false,
    NodeIterator: false,
    NodeList: false,
    Notification: false,
    OfflineAudioCompletionEvent: false,
    OfflineAudioContext: false,
    offscreenBuffering: false,
    onbeforeunload: true,
    openDatabase: false,
    Option: false,
    OscillatorNode: false,
    outerHeight: false,
    outerWidth: false,
    PageTransitionEvent: false,
    pageXOffset: false,
    pageYOffset: false,
    PasswordCredential: false,
    Path2D: false,
    Performance: false,
    PerformanceEntry: false,
    PerformanceMark: false,
    PerformanceMeasure: false,
    PerformanceNavigation: false,
    PerformanceResourceTiming: false,
    PerformanceTiming: false,
    PeriodicWave: false,
    Permissions: false,
    PermissionStatus: false,
    personalbar: false,
    Plugin: false,
    PluginArray: false,
    PopStateEvent: false,
    postMessage: false,
    ProcessingInstruction: false,
    ProgressEvent: false,
    PromiseRejectionEvent: false,
    prompt: false,
    PushManager: false,
    PushSubscription: false,
    RadioNodeList: false,
    Range: false,
    ReadableByteStream: false,
    ReadableStream: false,
    removeEventListener: false,
    Request: false,
    requestAnimationFrame: false,
    requestIdleCallback: false,
    resizeBy: false,
    resizeTo: false,
    Response: false,
    RTCIceCandidate: false,
    RTCSessionDescription: false,
    RTCPeerConnection: false,
    Screen: false,
    screenLeft: false,
    ScreenOrientation: false,
    screenTop: false,
    screenX: false,
    screenY: false,
    ScriptProcessorNode: false,
    scroll: false,
    scrollbars: false,
    scrollBy: false,
    scrollTo: false,
    scrollX: false,
    scrollY: false,
    SecurityPolicyViolationEvent: false,
    Selection: false,
    ServiceWorker: false,
    ServiceWorkerContainer: false,
    ServiceWorkerRegistration: false,
    sessionStorage: false,
    setInterval: false,
    setTimeout: false,
    ShadowRoot: false,
    SharedKeyframeList: false,
    SharedWorker: false,
    showModalDialog: false,
    SiteBoundCredential: false,
    speechSynthesis: false,
    SpeechSynthesisEvent: false,
    SpeechSynthesisUtterance: false,
    Storage: false,
    StorageEvent: false,
    styleMedia: false,
    StyleSheet: false,
    StyleSheetList: false,
    SubtleCrypto: false,
    SVGAElement: false,
    SVGAltGlyphDefElement: false,
    SVGAltGlyphElement: false,
    SVGAltGlyphItemElement: false,
    SVGAngle: false,
    SVGAnimateColorElement: false,
    SVGAnimatedAngle: false,
    SVGAnimatedBoolean: false,
    SVGAnimatedEnumeration: false,
    SVGAnimatedInteger: false,
    SVGAnimatedLength: false,
    SVGAnimatedLengthList: false,
    SVGAnimatedNumber: false,
    SVGAnimatedNumberList: false,
    SVGAnimatedPathData: false,
    SVGAnimatedPoints: false,
    SVGAnimatedPreserveAspectRatio: false,
    SVGAnimatedRect: false,
    SVGAnimatedString: false,
    SVGAnimatedTransformList: false,
    SVGAnimateElement: false,
    SVGAnimateMotionElement: false,
    SVGAnimateTransformElement: false,
    SVGAnimationElement: false,
    SVGCircleElement: false,
    SVGClipPathElement: false,
    SVGColor: false,
    SVGColorProfileElement: false,
    SVGColorProfileRule: false,
    SVGComponentTransferFunctionElement: false,
    SVGCSSRule: false,
    SVGCursorElement: false,
    SVGDefsElement: false,
    SVGDescElement: false,
    SVGDiscardElement: false,
    SVGDocument: false,
    SVGElement: false,
    SVGElementInstance: false,
    SVGElementInstanceList: false,
    SVGEllipseElement: false,
    SVGEvent: false,
    SVGExternalResourcesRequired: false,
    SVGFEBlendElement: false,
    SVGFEColorMatrixElement: false,
    SVGFEComponentTransferElement: false,
    SVGFECompositeElement: false,
    SVGFEConvolveMatrixElement: false,
    SVGFEDiffuseLightingElement: false,
    SVGFEDisplacementMapElement: false,
    SVGFEDistantLightElement: false,
    SVGFEDropShadowElement: false,
    SVGFEFloodElement: false,
    SVGFEFuncAElement: false,
    SVGFEFuncBElement: false,
    SVGFEFuncGElement: false,
    SVGFEFuncRElement: false,
    SVGFEGaussianBlurElement: false,
    SVGFEImageElement: false,
    SVGFEMergeElement: false,
    SVGFEMergeNodeElement: false,
    SVGFEMorphologyElement: false,
    SVGFEOffsetElement: false,
    SVGFEPointLightElement: false,
    SVGFESpecularLightingElement: false,
    SVGFESpotLightElement: false,
    SVGFETileElement: false,
    SVGFETurbulenceElement: false,
    SVGFilterElement: false,
    SVGFilterPrimitiveStandardAttributes: false,
    SVGFitToViewBox: false,
    SVGFontElement: false,
    SVGFontFaceElement: false,
    SVGFontFaceFormatElement: false,
    SVGFontFaceNameElement: false,
    SVGFontFaceSrcElement: false,
    SVGFontFaceUriElement: false,
    SVGForeignObjectElement: false,
    SVGGElement: false,
    SVGGeometryElement: false,
    SVGGlyphElement: false,
    SVGGlyphRefElement: false,
    SVGGradientElement: false,
    SVGGraphicsElement: false,
    SVGHKernElement: false,
    SVGICCColor: false,
    SVGImageElement: false,
    SVGLangSpace: false,
    SVGLength: false,
    SVGLengthList: false,
    SVGLinearGradientElement: false,
    SVGLineElement: false,
    SVGLocatable: false,
    SVGMarkerElement: false,
    SVGMaskElement: false,
    SVGMatrix: false,
    SVGMetadataElement: false,
    SVGMissingGlyphElement: false,
    SVGMPathElement: false,
    SVGNumber: false,
    SVGNumberList: false,
    SVGPaint: false,
    SVGPathElement: false,
    SVGPathSeg: false,
    SVGPathSegArcAbs: false,
    SVGPathSegArcRel: false,
    SVGPathSegClosePath: false,
    SVGPathSegCurvetoCubicAbs: false,
    SVGPathSegCurvetoCubicRel: false,
    SVGPathSegCurvetoCubicSmoothAbs: false,
    SVGPathSegCurvetoCubicSmoothRel: false,
    SVGPathSegCurvetoQuadraticAbs: false,
    SVGPathSegCurvetoQuadraticRel: false,
    SVGPathSegCurvetoQuadraticSmoothAbs: false,
    SVGPathSegCurvetoQuadraticSmoothRel: false,
    SVGPathSegLinetoAbs: false,
    SVGPathSegLinetoHorizontalAbs: false,
    SVGPathSegLinetoHorizontalRel: false,
    SVGPathSegLinetoRel: false,
    SVGPathSegLinetoVerticalAbs: false,
    SVGPathSegLinetoVerticalRel: false,
    SVGPathSegList: false,
    SVGPathSegMovetoAbs: false,
    SVGPathSegMovetoRel: false,
    SVGPatternElement: false,
    SVGPoint: false,
    SVGPointList: false,
    SVGPolygonElement: false,
    SVGPolylineElement: false,
    SVGPreserveAspectRatio: false,
    SVGRadialGradientElement: false,
    SVGRect: false,
    SVGRectElement: false,
    SVGRenderingIntent: false,
    SVGScriptElement: false,
    SVGSetElement: false,
    SVGStopElement: false,
    SVGStringList: false,
    SVGStylable: false,
    SVGStyleElement: false,
    SVGSVGElement: false,
    SVGSwitchElement: false,
    SVGSymbolElement: false,
    SVGTests: false,
    SVGTextContentElement: false,
    SVGTextElement: false,
    SVGTextPathElement: false,
    SVGTextPositioningElement: false,
    SVGTitleElement: false,
    SVGTransform: false,
    SVGTransformable: false,
    SVGTransformList: false,
    SVGTRefElement: false,
    SVGTSpanElement: false,
    SVGUnitTypes: false,
    SVGURIReference: false,
    SVGUseElement: false,
    SVGViewElement: false,
    SVGViewSpec: false,
    SVGVKernElement: false,
    SVGZoomAndPan: false,
    SVGZoomEvent: false,
    Text: false,
    TextDecoder: false,
    TextEncoder: false,
    TextEvent: false,
    TextMetrics: false,
    TextTrack: false,
    TextTrackCue: false,
    TextTrackCueList: false,
    TextTrackList: false,
    TimeEvent: false,
    TimeRanges: false,
    toolbar: false,
    Touch: false,
    TouchEvent: false,
    TouchList: false,
    TrackEvent: false,
    TransitionEvent: false,
    TreeWalker: false,
    UIEvent: false,
    URL: false,
    URLSearchParams: false,
    ValidityState: false,
    VTTCue: false,
    WaveShaperNode: false,
    WebGLActiveInfo: false,
    WebGLBuffer: false,
    WebGLContextEvent: false,
    WebGLFramebuffer: false,
    WebGLProgram: false,
    WebGLRenderbuffer: false,
    WebGLRenderingContext: false,
    WebGLShader: false,
    WebGLShaderPrecisionFormat: false,
    WebGLTexture: false,
    WebGLUniformLocation: false,
    WebSocket: false,
    WheelEvent: false,
    window: false,
    Window: false,
    Worker: false,
    XDomainRequest: false,
    XMLDocument: false,
    XMLHttpRequest: false,
    XMLHttpRequestEventTarget: false,
    XMLHttpRequestProgressEvent: false,
    XMLHttpRequestUpload: false,
    XMLSerializer: false,
    XPathEvaluator: false,
    XPathException: false,
    XPathExpression: false,
    XPathNamespace: false,
    XPathNSResolver: false,
    XPathResult: false,
    XSLTProcessor: false,
  },

  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
      generators: true,
      experimentalObjectRestSpread: true,
    },
  },

  settings: {
    'import/ignore': ['node_modules'],
    'import/extensions': ['.js'],
    'import/resolver': {
      node: {
        extensions: ['.js', '.json'],
      },
    },
  },

  rules: {
    // http://eslint.org/docs/rules/
    'array-callback-return': 'warn',
    'default-case': ['warn', { commentPattern: '^no default$' }],
    'dot-location': ['warn', 'property'],
    eqeqeq: ['warn', 'allow-null'],
    'new-parens': 'warn',
    'no-array-constructor': 'warn',
    'no-caller': 'warn',
    'no-cond-assign': ['warn', 'always'],
    'no-const-assign': 'warn',
    'no-control-regex': 'warn',
    'no-delete-var': 'warn',
    'no-dupe-args': 'warn',
    'no-dupe-class-members': 'warn',
    'no-dupe-keys': 'warn',
    'no-duplicate-case': 'warn',
    'no-empty-character-class': 'warn',
    'no-empty-pattern': 'warn',
    'no-eval': 'warn',
    'no-ex-assign': 'warn',
    'no-extend-native': 'warn',
    'no-extra-bind': 'warn',
    'no-extra-label': 'warn',
    'no-fallthrough': 'warn',
    'no-func-assign': 'warn',
    'no-implied-eval': 'warn',
    'no-invalid-regexp': 'warn',
    'no-iterator': 'warn',
    'no-label-var': 'warn',
    'no-labels': ['warn', { allowLoop: true, allowSwitch: false }],
    'no-lone-blocks': 'warn',
    'no-loop-func': 'warn',
    'no-mixed-operators': [
      'warn',
      {
        groups: [
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: false,
      },
    ],
    'no-multi-str': 'warn',
    'no-native-reassign': 'warn',
    'no-negated-in-lhs': 'warn',
    'no-new-func': 'warn',
    'no-new-object': 'warn',
    'no-new-symbol': 'warn',
    'no-new-wrappers': 'warn',
    'no-obj-calls': 'warn',
    'no-octal': 'warn',
    'no-octal-escape': 'warn',
    'no-redeclare': 'warn',
    'no-regex-spaces': 'warn',
    'no-restricted-syntax': ['warn', 'WithStatement'],
    'no-script-url': 'warn',
    'no-self-assign': 'warn',
    'no-self-compare': 'warn',
    'no-sequences': 'warn',
    'no-shadow-restricted-names': 'warn',
    'no-sparse-arrays': 'warn',
    'no-template-curly-in-string': 'warn',
    'no-this-before-super': 'warn',
    'no-throw-literal': 'warn',
    'no-undef': 'error',
    'no-restricted-globals': ['error', 'event'],
    'no-unexpected-multiline': 'warn',
    'no-unreachable': 'warn',
    'no-unused-expressions': [
      'warn',
      {
        allowShortCircuit: true,
        allowTernary: true,
      },
    ],
    'no-unused-labels': 'warn',
    'no-unused-vars': [
      'warn',
      {
        args: 'none',
        ignoreRestSiblings: true,
      },
    ],
    'no-use-before-define': ['warn', 'nofunc'],
    'no-useless-computed-key': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-rename': [
      'warn',
      {
        ignoreDestructuring: false,
        ignoreImport: false,
        ignoreExport: false,
      },
    ],
    'no-with': 'warn',
    'no-whitespace-before-property': 'warn',
    'operator-assignment': ['warn', 'always'],
    radix: 'warn',
    'require-yield': 'warn',
    'rest-spread-spacing': ['warn', 'never'],
    strict: ['warn', 'never'],
    'unicode-bom': ['warn', 'never'],
    'use-isnan': 'warn',
    'valid-typeof': 'warn',
    'no-restricted-properties': [
      'error',
      {
        object: 'require',
        property: 'ensure',
        message: 'Please use import() instead. More info: https://webpack.js.org/guides/code-splitting-import/#dynamic-import',
      },
      {
        object: 'System',
        property: 'import',
        message: 'Please use import() instead. More info: https://webpack.js.org/guides/code-splitting-import/#dynamic-import',
      },
    ],

    // https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/

    // TODO: import rules are temporarily disabled because they don't play well
    // with how eslint-loader only checks the file you change. So if module A
    // imports module B, and B is missing a default export, the linter will
    // record this as an issue in module A. Now if you fix module B, the linter
    // will not be aware that it needs to re-lint A as well, so the error
    // will stay until the next restart, which is really confusing.

    // This is probably fixable with a patch to eslint-loader.
    // When file A is saved, we want to invalidate all files that import it
    // *and* that currently have lint errors. This should fix the problem.
    // (As an exception, import/no-webpack-loader-syntax can be enabled already
    // because it doesn't depend on whether the file exists, so this issue
    // doesn't apply to it.)

    // 'import/default': 'warn',
    // 'import/export': 'warn',
    // 'import/named': 'warn',
    // 'import/namespace': 'warn',
    // 'import/no-amd': 'warn',
    // 'import/no-duplicates': 'warn',
    // 'import/no-extraneous-dependencies': 'warn',
    // 'import/no-named-as-default': 'warn',
    // 'import/no-named-as-default-member': 'warn',
    // 'import/no-unresolved': ['warn', { commonjs: true }],
    // We don't support configuring Webpack using import source strings, so this
    // is always an error.
    'import/no-webpack-loader-syntax': 'error',

    // https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
    'react/jsx-equals-spacing': ['warn', 'never'],
    'react/jsx-no-duplicate-props': ['warn', { ignoreCase: true }],
    'react/jsx-no-undef': 'error',
    'react/jsx-pascal-case': [
      'warn',
      {
        allowAllCaps: true,
        ignore: [],
      },
    ],
    'react/jsx-uses-react': 'warn',
    'react/jsx-uses-vars': 'warn',
    'react/no-danger-with-children': 'warn',
    'react/no-deprecated': 'warn',
    'react/no-direct-mutation-state': 'warn',
    'react/no-is-mounted': 'warn',
    'react/react-in-jsx-scope': 'error',
    'react/require-render-return': 'warn',
    'react/style-prop-object': 'warn',

    // https://github.com/evcohen/eslint-plugin-jsx-a11y/tree/master/docs/rules
    'jsx-a11y/aria-role': 'warn',
    'jsx-a11y/img-has-alt': 'warn',
    'jsx-a11y/img-redundant-alt': 'warn',
    'jsx-a11y/no-access-key': 'warn',

    // https://github.com/gajus/eslint-plugin-flowtype
    'flowtype/define-flow-type': 'warn',
    'flowtype/require-valid-file-annotation': 'warn',
    'flowtype/use-flow-type': 'warn',
  },
};
